import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppProvider } from "../provider/AppProvider";
import "./app.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Project Film",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="p-0 m-0 bg-white">
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
